[ci-cd] Edit job

diff --git a/.github/workflows/base.yml b/.github/workflows/base.yml
--- a/.github/workflows/base.yml
+++ b/.github/workflows/base.yml
@@ -28,5 +28,20 @@ jobs:
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          echo "running prerequisites"
+          ./scripts/pre-requisites.sh -s
+          echo "finished prerequisites"
+          md="test/example.md"
+          css="test/example.css"
+          pdf="test/example.pdf"
+          html="test/example.html"
+          echo "running script"
+          ./scripts/generate.sh -s -m $md -c $css -p $pdf -o $html
+          echo "finished script"
+          if [[ -f $pdf ]] && [[ -f $html ]]; then
+            echo "tests finished ok"
+            exit 0
+          else
+            echo "test finished with error"
+            exit 1
+          fi
